# Generated by Django 2.2.7 on 2019-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frients', '0003_auto_20191203_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='describe',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
