# Generated by Django 2.2.7 on 2019-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frients', '0004_auto_20191203_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='communicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('username2', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='describe',
            field=models.CharField(blank=True, default=True, max_length=1000),
        ),
    ]
